export const CATEGORY_LIST_REQUEST = 'CATEGORY_LIST_REQUEST'
export const CATEGORY_LIST_SUCCESS = 'CATEGORY_LIST_SUCCESS'
export const CATEGORY_LIST_FAIL = 'CATEGORY_LIST_FAIL'

export const CATEGORY_LIST_INCOME_REQUEST = 'CATEGORY_LIST_INCOME_REQUEST'
export const CATEGORY_LIST_INCOME_SUCCESS = 'CATEGORY_LIST_INCOME_SUCCESS'
export const CATEGORY_LIST_INCOME_FAIL = 'CATEGORY_LIST_INCOME_FAIL'

export const CATEGORY_ADD_INCOME_REQUEST = 'CATEGORY_ADD_INCOME_REQUEST'
export const CATEGORY_ADD_INCOME_SUCCESS = 'CATEGORY_ADD_INCOME_SUCCESS'
export const CATEGORY_ADD_INCOME_FAIL = 'CATEGORY_ADD_INCOME_FAIL'

export const CATEGORY_UPDATE_REQUEST = 'CATEGORY_UPDATE_REQUEST'
export const CATEGORY_UPDATE_SUCCESS = 'CATEGORY_UPDATE_SUCCESS'
export const CATEGORY_UPDATE_FAIL = 'CATEGORY_UPDATE_FAIL'

export const CATEGORY_DELETE_REQUEST = 'CATEGORY_DELETE_REQUEST'
export const CATEGORY_DELETE_SUCCESS = 'CATEGORY_DELETE_SUCCESS'
export const CATEGORY_DELETE_FAIL = 'CATEGORY_DELETE_FAIL'

export const CATEGORY_LIST_EXPENSES_REQUEST = 'CATEGORY_LIST_EXPENSES_REQUEST'
export const CATEGORY_LIST_EXPENSES_SUCCESS = 'CATEGORY_LIST_EXPENSES_SUCCESS'
export const CATEGORY_LIST_EXPENSES_FAIL = 'CATEGORY_LIST_EXPENSES_FAIL'

export const CATEGORY_ADD_EXPENSES_REQUEST = 'CATEGORY_ADD_EXPENSES_REQUEST'
export const CATEGORY_ADD_EXPENSES_SUCCESS = 'CATEGORY_ADD_EXPENSES_SUCCESS'
export const CATEGORY_ADD_EXPENSES_FAIL = 'CATEGORY_ADD_EXPENSES_FAIL'

export const CATEGORY_LIST_TOTAL_REQUEST = 'CATEGORY_LIST_TOTAL_REQUEST'
export const CATEGORY_LIST_TOTAL_SUCCESS = 'CATEGORY_LIST_TOTAL_SUCCESS'
export const CATEGORY_LIST_TOTAL_FAIL = 'CATEGORY_LIST_TOTAL_FAIL'
