export const TRANSACTION_INCOME_LIST_REQUEST = 'TRANSACTION_INCOME_LIST_REQUEST'
export const TRANSACTION_INCOME_LIST_SUCCESS = 'TRANSACTION_INCOME_LIST_SUCCESS'
export const TRANSACTION_INCOME_LIST_FAIL = 'TRANSACTION_INCOME_LIST_FAIL'

export const TRANSACTION_ADD_REQUEST = 'TRANSACTION_ADD_REQUEST'
export const TRANSACTION_ADD_SUCCESS = 'TRANSACTION_ADD_SUCCESS'
export const TRANSACTION_ADD_FAIL = 'TRANSACTION_ADD_FAIL'

export const TRANSACTION_UPDATE_REQUEST = 'TRANSACTION_UPDATE_REQUEST'
export const TRANSACTION_UPDATE_SUCCESS = 'TRANSACTION_UPDATE_SUCCESS'
export const TRANSACTION_UPDATE_FAIL = 'TRANSACTION_UPDATE_FAIL'

export const TRANSACTION_DELETE_REQUEST = 'TRANSACTION_DELETE_REQUEST'
export const TRANSACTION_DELETE_SUCCESS = 'TRANSACTION_DELETE_SUCCESS'
export const TRANSACTION_DELETE_FAIL = 'TRANSACTION_DELETE_FAIL'

export const TRANSACTION_EXPENSES_LIST_REQUEST =
  'TRANSACTION_EXPENSES_LIST_REQUEST'
export const TRANSACTION_EXPENSES_LIST_SUCCESS =
  'TRANSACTION_EXPENSES_LIST_SUCCESS'
export const TRANSACTION_EXPENSES_LIST_FAIL = 'TRANSACTION_EXPENSES_LIST_FAIL'

export const TRANSACTION_TREND_LIST_REQUEST = 'TRANSACTION_TREND_LIST_REQUEST'
export const TRANSACTION_TREND_LIST_SUCCESS = 'TRANSACTION_TREND_LIST_SUCCESS'
export const TRANSACTION_TREND_LIST_FAIL = 'TRANSACTION_TREND_LIST_FAIL'

export const TRANSACTION_RECORDS_REQUEST = 'TRANSACTION_RECORDS_REQUEST'
export const TRANSACTION_RECORDS_SUCCESS = 'TRANSACTION_RECORDS_SUCCESS'
export const TRANSACTION_RECORDS_FAIL = 'TRANSACTION_RECORDS_FAIL'
